### ISSUE TITLE
Not working in iOS 17?

### ISSUE THREAD

**Issue by ELezov** [prongbang/ScreenProtectorKit#6]
I have tried on iOS 16.1 - perfect work, but it is not working on iOS 17.

Can you suggest me other way for solving this issue?

**Comment by BLAZ3R** [comment]
@ELezov Hi, have you able to fix it?

**Comment by flutberry** [comment]
@ELezov Hi, have you been able to fix it?

**Comment by mdynia111** [comment]
Similar issue mentioned here: https://stackoverflow.com/questions/77140471/prevent-screenshot-with-issecuretextentry-is-not-working-on-ios-17

**Comment by bmatthys** [comment]
I have the same issue and creating a fork with the fix @mdynia111 proposed doesn't do the trick. Anybody else any ideas?

**Comment by iqbalmineraltown** [comment]
coming from Flutter package, I tried this solution https://github.com/prongbang/screen_protector/issues/22#issuecomment-1742477626 

It worked on the iOS 17 simulator but haven't tested it on physical device

**Comment by prongbang** [comment]
Thank you for reporting the issue. We will address it as quickly as possible.

**Comment by prongbang** [comment]
Resolved in version 1.3.1, Thank you for reporting the issue.
